---
title: "Plot Results"
author: "Naman Agrawal"
date: "2024-06-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stringr)
library(MCMCpack)
library(LaplacesDemon)
library(invgamma)
library(tidyverse)
library(HDInterval)
library(tidyverse)

```

## MSE


```{r, eval = F}
# Add results to dataframe
df <- df %>%
  mutate(
    smooth_elastic_mse = smooth_elastic_mse,
    smooth_elastic_bias = smooth_elastic_bias,
    smooth_elastic_variance = smooth_elastic_variance,
    power_mse = power_mse,
    power_bias = power_bias,
    power_variance = power_variance,
    normalized_power_mse = normalized_power_mse,
    normalized_power_bias = normalized_power_bias,
    normalized_power_variance = normalized_power_variance,
    commensurate_power_mse = commensurate_power_mse,
    commensurate_power_bias = commensurate_power_bias,
    commensurate_power_variance = commensurate_power_variance
  )

# Save the results
saveRDS(df, file = "../results_mse_n_delta.rds")
```



## MSE

```{r, echo=FALSE}
df = readRDS("../results_mse_n_delta.rds")
# Plot MSE
ggplot(data = df %>% 
         pivot_longer(cols = ends_with("mse"), names_to = "type", values_to = "mse_vals") %>%
         mutate(type = str_replace(type, "_", " "))) +
  geom_line(aes(x = delta, y = mse_vals, color = type)) +
  theme_bw() +
  labs(x = "δ", y = "MSE of Point Estimator", color = "Method") + 
  scale_colour_viridis_d()

# Plot MSE
ggplot(data = df %>% 
         pivot_longer(cols = ends_with("mse"), names_to = "type", values_to = "mse_vals") %>%
         mutate(type = str_replace(type, "_", " "))) +
  geom_line(aes(x = delta, y = mse_vals)) +
  theme_bw() +
  labs(x = "δ", y = "MSE of Point Estimator", color = "Method") +
  facet_wrap(~type, scales = "free_y") 

```

## Bias

```{r, echo=FALSE}
# Plot Bias
ggplot(data = df %>% 
         pivot_longer(cols = ends_with("bias"), names_to = "type", values_to = "bias_vals") %>%
         mutate(type = str_replace(type, "_", " "))) +
  geom_line(aes(x = delta, y = bias_vals, color = type)) +
  theme_bw() +
  labs(x = "δ", y = "Bias of Point Estimator", color = "Method") + 
  scale_colour_viridis_d()

# Plot Bias
ggplot(data = df %>% 
         pivot_longer(cols = ends_with("bias"), names_to = "type", values_to = "bias_vals") %>%
         mutate(type = str_replace(type, "_", " "))) +
  geom_line(aes(x = delta, y = bias_vals)) +
  theme_bw() +
  labs(x = "δ", y = "Bias of Point Estimator", color = "Method") +
  facet_wrap(~type, scales = "free_y") 
```

# Variance

```{r, echo=FALSE}
# Plot Variance
ggplot(data = df %>% 
         pivot_longer(cols = ends_with("variance"), names_to = "type", values_to = "variance_vals") %>%
         mutate(type = str_replace(type, "_", " "))) +
  geom_line(aes(x = delta, y = variance_vals, color = type)) +
  theme_bw() +
  labs(x = "δ", y = "Variance of Point Estimator", color = "Method") + 
  scale_colour_viridis_d()

# Plot Variance
ggplot(data = df %>% 
         pivot_longer(cols = ends_with("variance"), names_to = "type", values_to = "variance_vals") %>%
         mutate(type = str_replace(type, "_", " "))) +
  geom_line(aes(x = delta, y = variance_vals)) +
  theme_bw() +
  labs(x = "δ", y = "Variance of Point Estimator", color = "Method") +
  facet_wrap(~type, scales = "free_y") 
```

